apiVersion: v1
kind: Secret
metadata:
  name: bgfbjjjj5555-secret
  namespace: bgfbjjjj5555
type: Opaque
data:
  rootpassword: ${{secret.ROOTPASSWORD}} | base64
  userpassword: ${{secret.USERPASSWORD}} | base64
